### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by hpeberhard** [DKMS-LSL/HLAsim#1] opened 2015-07-10 09:10 UTC
devtools::install_github("gschofl/HLAsim")
Downloading github repo gschofl/HLAsim@master
Installing HLAsim
Skipping 1 packages not available: purrr
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore CMD INSTALL  \
  '/private/var/folders/bt/1qz34dm91nzbt9tjqvr7qxz80000gn/T/RtmpvtOb9s/devtoolsf0325cc587/gschofl-HLAsim-349bbc6'  \
  --library='/Library/Frameworks/R.framework/Versions/3.2/Resources/library'  \
  --install-tests 
- installing _source_ package ‘HLAsim’ ...
  *\* libs
  clang++ -std=c++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include"   -fPIC  -Wall -mtune=core2 -g -O2 -c RcppExports.cpp -o RcppExports.o
  clang++ -std=c++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include"   -fPIC  -Wall -mtune=core2 -g -O2 -c sort-hla.cpp -o sort-hla.o
  clang++ -std=c++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o HLAsim.so RcppExports.o sort-hla.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
  installing to /Library/Frameworks/R.framework/Versions/3.2/Resources/library/HLAsim/libs
  *\* R
  *\* data
  **\* moving datasets to lazyload DB
  Warning: replacing previous import by ‘dplyr::between’ when loading ‘HLAsim’
  Warning: replacing previous import by ‘dplyr::last’ when loading ‘HLAsim’
  Warning: namespace ‘HLAsim’ is not available and has been replaced
  by .GlobalEnv when processing object ‘dpb1’
  Warning: namespace ‘orcl’ is not available and has been replaced
  by .GlobalEnv when processing object ‘dpb1’
  Warning: replacing previous import by ‘dplyr::between’ when loading ‘HLAsim’
  Warning: replacing previous import by ‘dplyr::last’ when loading ‘HLAsim’
  Warning: namespace ‘HLAsim’ is not available and has been replaced
  by .GlobalEnv when processing object ‘dpb1’
  Warning: namespace ‘orcl’ is not available and has been replaced
  by .GlobalEnv when processing object ‘dpb1’
  Warning: replacing previous import by ‘dplyr::between’ when loading ‘HLAsim’
  Warning: replacing previous import by ‘dplyr::last’ when loading ‘HLAsim’
  Warning: namespace ‘HLAsim’ is not available and has been replaced
  by .GlobalEnv when processing object ‘dqb1’
  Warning: namespace ‘orcl’ is not available and has been replaced
  by .GlobalEnv when processing object ‘dqb1’
  Warning: replacing previous import by ‘dplyr::between’ when loading ‘HLAsim’
  Warning: replacing previous import by ‘dplyr::last’ when loading ‘HLAsim’
  Warning: namespace ‘HLAsim’ is not available and has been replaced
  by .GlobalEnv when processing object ‘dqb1’
  Warning: namespace ‘orcl’ is not available and has been replaced
  by .GlobalEnv when processing object ‘dqb1’
  Warning: replacing previous import by ‘dplyr::between’ when loading ‘HLAsim’
  Warning: replacing previous import by ‘dplyr::last’ when loading ‘HLAsim’
  Warning: namespace ‘HLAsim’ is not available and has been replaced
  by .GlobalEnv when processing object ‘drb1’
  Warning: namespace ‘orcl’ is not available and has been replaced
  by .GlobalEnv when processing object ‘drb1’
  Warning: replacing previous import by ‘dplyr::between’ when loading ‘HLAsim’
  Warning: replacing previous import by ‘dplyr::last’ when loading ‘HLAsim’
  Warning: namespace ‘HLAsim’ is not available and has been replaced
  by .GlobalEnv when processing object ‘drb1’
  Warning: namespace ‘orcl’ is not available and has been replaced
  by .GlobalEnv when processing object ‘drb1’
  *\* preparing package for lazy loading
  Warning: replacing previous import by ‘dplyr::between’ when loading ‘HLAsim’
  Warning: replacing previous import by ‘dplyr::last’ when loading ‘HLAsim’
  *\* help
  **\* installing help indices
  *\* building package indices
  *\* testing if installed package can be loaded
  Warning: replacing previous import by ‘dplyr::between’ when loading ‘HLAsim’
  Warning: replacing previous import by ‘dplyr::last’ when loading ‘HLAsim’
  Error in namespaceExport(ns, exports) : 
  undefined exports: get_testdata, make_test_instance, make_test_instance2
  Fehler: Laden fehlgeschlagen
  Ausführung angehalten
  ERROR: loading failed
- removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/HLAsim’
  Fehler: Command failed (1)

**Comment by gschofl** [comment] 2015-07-13 15:33
The issue seems to have been the NAMESPACE file still trying to export a function that didn't exist any more. This should now be fixed.

Also note, that HLAsim depends on a package, `purrr`, that is not yet available from CRAN and therefore will not be automatically installed.

Do `install_github("hadley/purrr")` before installing HLAsim.

I updated the README accordingly

**Comment by hpeberhard** [comment] 2015-07-14 07:13
Thanks. The HLAsim library installs and is partly usable. Two things:

1) After installing and loading purr, search() yields:
 [1] ".GlobalEnv"        "package:purrr"     "package:stats"

but the package is not detected during install, also namespace orcl is not available.

devtools::install_github("gschofl/HLAsim")
Downloading github repo gschofl/HLAsim@master
Installing HLAsim
Skipping 1 packages not available: purrr
...
Warning: namespace ‘orcl’ is not available and has been replaced
by .GlobalEnv when processing object ‘dpb1’
...
*\* testing if installed package can be loaded
- DONE (HLAsim)

2) sample_drb_de <- make_genotype_sampler(drb1[provenance == "DE"], drb1_eag1412)
Error in loadNamespace(name) : there is no package called ‘orcl’

I was not able to find a package named orcl on the internet.

**Comment by gschofl** [comment] 2015-07-14 09:26
The warnings you can ignore. The first one seems to crop up only  when you manually install a dependency in the same session whenever a package depends on another package not in any of the canonical repositories. It should go away at subsequent installs.

`orcl` is the R interface to the internal databases at DKMS LSL. Since the data the paper is based upon is included in the package, the core functionality of `HLAsim` is supposed to work without `orcl`.  

The warnings about `orcl` when the data objects get loaded should be fine. There still where some bits and bobs, however, that made calls to functions in the `orcl` namespace when they clearly shouldn't. I hope I have caught them all in the latest commit. 

On my machine at least the code in the vignette runs now through without throwing errors with `orcl` removed.

**Comment by hpeberhard** [comment] 2015-07-14 14:39
Sorry for being a pain in the neck. 

Everything worked like expected but then I got:

Error in eval(expr, envir, enclos) : 
  'nzchar()' benötigt einen Charakter-Vektor

in tables.r:g_table <- function()

and later strplit also failed, so I used colClasses reading the csv to make it work:

rs <- read.csv(u, header = FALSE, colClasses="character", sep = ";", comment.char = "#")

However, only to get the following error later:

Error in if (is.na(x = a)) return(eag_numbers(NA, NA)) : 
  Argument hat Länge 0
Zusätzlich: Warning message:
In is.na(x = a) :
  is.na() auf nicht-(Liste oder Vektor) des Typs 'NULL' angewendet

> traceback()
> 15: f(...)
> 14: remap(.)
> 13: is.factor(x) at utils.r#6
> 12: nunique(nums[1:2])
> 11: paste0(nunique(nums[1:2]), nunique(nums[3:4])) at inject-errors.r#245
> 10: eag_status(remap(.))
> 9: FUN(X[[i]], ...)
> 8: lapply(.x, .f, ...)
> 7: eval(expr, envir, enclos)
> 6: eval(lhs, parent, parent)
> 5: lapply(.x, .f, ...) %>% output_hook(.x)
> 4: purrr::map(unique_remapped_genotypes, ~eag_status(remap(.)))
> 3: unlist(purrr::map(unique_remapped_genotypes, ~eag_status(remap(.))))
> 2: data.table(genotype = unique_genotypes, genotype2 = allele2string(unique_remapped_genotypes), 
>        eag_status = unlist(purrr::map(unique_remapped_genotypes, 
>            ~eag_status(remap(.))))) at geno-table.r#88
> 1: make_genotype_sampler(drb1[provenance == "DE"], drb1_eag1412)

The data structure unique_remapped_genotypes looks good on first sight. So, I will leave it for today.

**Comment by gschofl** [comment] 2015-07-14 15:22
>  Sorry for being a pain in the neck.

That's no problem :-)

What the function `g_table()` does is to go to http://hla.alleles.org/wmda to fetch and parse the latest G group codes. The code so far didn't try to saveguard against connectivity problems. I believe what you were experiencing were the result of some HTTP error that dripped up the parser.

The latest revision should fail early with a meaningful error message if it is indeed the internet that's causing the trouble

**Comment by hpeberhard** [comment] 2015-07-15 08:40
It probably wasn't the internet connection (alone). 

Below are the patches I had to apply in order to run the code in vignettes/introduction.Rmd for provenance DE and drb1.

diff -ubB HLAsim-master-2/R/inject-errors.r HLAsim-master/R/inject-errors.r
--- HLAsim-master-2/R/inject-errors.r   2015-07-14 08:07:10.000000000 +0200
+++ HLAsim-master/R/inject-errors.r 2015-07-15 10:22:58.000000000 +0200
@@ -115,7 +115,7 @@
   dt <- rs[rs2, allow.cartesian = TRUE]
   dt <- dt[!is.na(genotype)]
   dt[, c("genotype", "eag_status") := do_inject(dt, mapargs)]
-  dt[, zygosity := ifelse(HLA::is_homozygous(genotype), "homozygous", "heterozygous")]
-  dt[, zygosity := ifelse(is_homozygous(genotype), "homozygous", "heterozygous")]
  dt[, genotype := ifelse(genotype == "NA/NA", NA_character_, genotype)]
  dt[, zygosity := ifelse(is.na(genotype), NA_character_,  zygosity)]
  dt[, conc := NULL]
  diff -ubB HLAsim-master-2/R/remapper.r HLAsim-master/R/remapper.r
  --- HLAsim-master-2/R/remapper.r    2015-07-14 08:07:10.000000000 +0200
  +++ HLAsim-master/R/remapper.r  2015-07-15 10:10:55.000000000 +0200
  @@ -58,7 +58,7 @@
  enp <- ex3[, .(prob = .N/nrow(ex3)), by = eag_num]
  
  structure(memoise(function(a) {
-    if (is.na(x = a))
-    if (is.null(x = a) || is.na(x = a))
     return(eag_numbers(NA, NA))
  
   a1   <- allele(a, 1)
  diff -ubB HLAsim-master-2/R/tables.r HLAsim-master/R/tables.r
  --- HLAsim-master-2/R/tables.r  2015-07-14 08:07:10.000000000 +0200
  +++ HLAsim-master/R/tables.r    2015-07-15 09:42:24.000000000 +0200
  @@ -71,7 +71,7 @@
   warning("Possibly malformed file \"hla_nom_g.txt\" ",
           "downloaded from http://hla.alleles.org.", immediate. = TRUE)
  }
-  rs <- read.csv(con, header = FALSE, sep = ";", comment.char = "#")
-  rs <- read.csv(con, header = FALSE, sep = ";", colClasses="character", comment.char = "#")
  rs <- dplyr::tbl_dt(data.table::setDT(rs))
  data.table::setnames(rs, names(rs), c("gene", "subtype", "code"))
  rs <- rs[, gene := paste0("HLA-", sub("*", "", gene, fixed = TRUE))]

I did not bother for the mappability errors though, since they had no noticeable influence for me:

sample_drb_de <- make_genotype_sampler(drb1[provenance == "DE"], drb1_eag1412)
Creating lookup table and mappers ...

Fetching NMDP codes ...
Fetching G-Codes ...
Ensuring mappability of 3194 genotypes. This step will take a while ...

  |=======                                                                            |   9%
Error 'invalid first argument' in 272
  |==================                                                                 |  22%
Error 'invalid first argument' in 704
  |==========================                                                         |  31%
Error 'invalid first argument' in 1002
  |=============================                                                      |  35%
Error 'invalid first argument' in 1129
  |=====================================                                              |  45%
Error 'invalid first argument' in 1439
  |==========================================                                         |  50%
Error 'invalid first argument' in 1598
  |===========================================                                        |  52%
Error 'invalid first argument' in 1672
  |=============================================                                      |  55%
Error 'invalid first argument' in 1746
  |===============================================                                    |  56%
Error 'invalid first argument' in 1797
  |================================================                                   |  58%
Error 'invalid first argument' in 1839
Error 'invalid first argument' in 1858
  |==================================================                                 |  61%
Error 'invalid first argument' in 1939
  |=====================================================                              |  63%
Error 'invalid first argument' in 2022
  |=========================================================                          |  68%
Error 'invalid first argument' in 2177
Error 'invalid first argument' in 2181
  |===========================================================                        |  71%
Error 'invalid first argument' in 2257
  |==================================================================                 |  80%
Error 'invalid first argument' in 2550
Error 'invalid first argument' in 2557
  |===================================================================================| 100%

**Comment by gschofl** [comment] 2015-07-15 16:16
Would you mind posting the output of your `sessionInfo()` here? Except for the first diff (where `is_homozygous()` got dragged in from a package of helper functions that only exists locally), I cannot reproduce any of the problems on my machine. It might be differences in the versions of some packages, it might be differences in the OS.

**Comment by gschofl** [comment] 2015-07-15 20:22
I believe I found the problem and it should be fixed in the latest commit. In the most recent edition of the G-code table a G-code for DRB1 (11:11:01G) expands (for whatever reason) to a single subtype (11:11:01). This weird case broke a lookup function and caused all kind of trouble downstream. 

It simply didn't happen to me, as I've been using a somewhat older local copy of the G-code table where this kind of scenario never occurred.

**Comment by hpeberhard** [comment] 2015-07-16 06:29
Confirmed. The latest commit runs the code in vignettes/introduction.Rmd for provenance DE and drb1 and dqb1 without any issues. 
Great job!

P.S.: the single subtypes for G- or P-codes occur when all alleles but one get deleted from the group over time.

**Closed as completed** 2015-07-16 06:30 UTC
